# Generated by Django 4.2 on 2024-04-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.news'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='views_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во просмотров'),
        ),
    ]
