# Generated by Django 4.2 on 2024-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
